on:
  pull_request:
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          API_TYPE: "azure"
          DEPLOYMENT_ID: "gpt-4" # custom name of the deployed model on Azure
          OPENAI_KEY: ${{ secrets.AZURE_API_KEY }}
          API_BASE: ${{ secrets.API_BASE }}
          API_VERSION: ${{ secrets.API_VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}